/*
Second task - Sum of Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
namespace Solutions;

public class SumOfEvenFibonacciNumbers
{

    public static int getSumOfEvenFibonacciNumbers(int maxValue)
    {
        if (maxValue < 2) return 0;

        int sum = 0;
        int a = 1, b = 2;

        while (a <= maxValue)
        {
            if (a % 2 == 0)
            {
                sum += a;
            }

            int temp = a;
            a = b;
            b = temp + b;
        }

        return sum;
    }

}